### ISSUE TITLE
Design RPC encoding for dual REST / Websocket

### ISSUE THREAD

**Issue by creationix** [virgo-agent-toolkit/super-agent#1]
The goal here is to design a method for encoding various RPC calls as either REST calls or commands to be send over a multiplexed websocket connection.

This needs to support the following abilities:
- endpoint name
- input with positional and named arguments and defaults for optional parameters 
- input values can be anything supported by msgpack (so JSON + binary)
- output can also be anything supported by msgpack
- output can also be an error message with error code.
- output can be a stream (which is then multiplexed over the existing or new websocket connection)

We need to define the multiplexing protocol for websocket in addition to the RPC commands.

**Comment by creationix** [comment]
Let's start out with some sample APIs
- `createToken() -> token` - Has no input and returns a single string.
- `newPty(shell="/bin/bash", width=80, height=24) -> tty-stream` - Several optional inputs and returns a stream.
- `runCommand(command, stdin=false) -> {stdout,stderr,exitCode}` - outputs several values as a list.
- `readDir(path) -> {name,type}[]` - get files in directory with name and type.
- `stat(path) -> {type,size,mtime,mode,group,owner,...}` - Get more details about a file.
- `readFile(path) -> contents` - read file
- `writeFile(path, value,mode=0644,owner=root,group=root)` - write file, no output, but we want confirmation it happened.

**Comment by harageth** [comment]
How do we know which server this is running commands/tty on? That is handled through the session/token?

**Comment by kaustavha** [comment]
For the following api endpoints I recommend taking a look at the respective code:
`runCommand => [rackspace-monitoring-agent || virgo-base-agent]/hostinfo/misc/run || luvit/spawn/exec & execFile` 
`readDir => luvit-walk, there is an implementation of a recursive readdir in hostinfo somewhere`
`stat => hostinfo/fileperms, additionally PR #877 on rackspace-monitoring-agent extends fileperms to be able to take args`
`readFile => [rackspace-monitoring-agent || virgo-base-agent]/hostinfo/misc/read`
`writeFile => Iirc I documented this bit of the luvit api in the luvit docs`
Also do take a look at PR #877 on rackspace-monitoring-agent, it was a early sketchout of a remote execution feature on the monitoring agent I did a long time ago when I was bored.

**Comment by creationix** [comment]
Keep in mind this issue is just for the encoding format on the wire.  See the other two issues for the actual endpoints we want to design.  I just provided a few examples to guide the design with some real-world uses.

**Comment by creationix** [comment]
```
name(arg1, arg1, ...) -> result
```
- authentication will use headers

## REST Variant
- HTTP message is POST
- url path is name
- request is always array of positional arguments.
- response is single value
- request and response can be encoded as JSON or msgpack.
- defaults to JSON, but headers can specify otherwise.
- Use `application/msgpack` in standard HTTP headers to 
  opt in to format in connection.

## Websocket Variant
- connect with same auth and encoding headers as REST
- use subprotocol "virgo-rpc"
- request looks like `[id, name, arg1, arg2...]`
- response looks like `[-id, result]`

The AEP will handle re-mapping between clients and agents 
and remapping IDs.

Streams only work over msgpack and websocket.

When agents reply with streams, they will be encoded as 
opaque stream IDs. `{__stream__: sid}`
- agent sends `[sid, chunk]` (chunk is binary)
- client sends `[-sid, chunk]`
- to end a stream send nothing for chunk `[sid]`.

The AEP will be responsible for cleaning up orphaned
streams and sending proper shutdown messages if
disconnects happen.
- The aep will include a string reason if `[sid, reason]` 
  (reason is string)
