### ISSUE TITLE
Add Misc UV functions to agent

### ISSUE THREAD

**Issue by creationix** [virgo-agent-toolkit/super-agent#32]
Add platform wrappings for:
- [x] uv.getpid()
- [x] uv.getuid()
- [x] uv.getgid()
- [x] uv.get_free_memory()
- [x] uv.get_total_memory()
- [x] uv.cpu_info()
- [x] uv.interface_addresses()
- [x] uv.resident_set_memory()
- [x] uv.uptime()
- [x] uv.loadavg()
- [x] uv.os_homedir()

Since the luv docs may be lacking (not sure), you can also just run the commands in a terminal to see what shape the luv bindings output the data.  You'll need to make the API function match.

**Comment by harageth** [comment]
Also noted from our conversation today: we need support for encoding and decoding floats from msgpack for the aep. So loadavg wont be able to be implemented till that happens.

**Comment by creationix** [comment]
float parsing is done now.

**Comment by harageth** [comment]
I am moving this to the backlog since the last item on this list is not in luv yet

**Comment by creationix** [comment]
You could just remove that entry from the list.  Upstream libuv hasn't even been released yet.  I'm not sure why they pushed it to their docs already.  I asked on IRC several days ago and they said it would be out soon, but I still don't see it.
