### ISSUE TITLE
Implement Windows backend for pty function.

### ISSUE THREAD

**Issue by creationix** [virgo-agent-toolkit/super-agent#33]
We can use the same technique as done in pty.js https://github.com/chjj/pty.js/blob/master/src/win/pty.cc

**Comment by creationix** [comment]
This looks to be a bit more work than initially estimated, we'll need to spawn a special process in a hidden window and scrape it's output.  I was hoping to do all this from luajit's FFI interface, but it looks like we'll need to involve some actual C code.

**Comment by creationix** [comment]
![windows-test](https://cloud.githubusercontent.com/assets/89353/14126368/144ebb2e-f5d6-11e5-923c-6453da8fbd06.PNG)
WIth our fixes combined, windows agent is working (still need a custom client app for the spawn command you've been working on though)

**Comment by creationix** [comment]
And yes my computer's username is "Living Room".  My media box was the quickest windows machine for testing.

**Comment by creationix** [comment]
I also added a new button for spawning a file browser (since the terminal doesn't work yet).  Looks like the non-terminal APIs are working great on windows.

![windows-image-test](https://cloud.githubusercontent.com/assets/89353/14126932/ec50a570-f5d9-11e5-9e0e-b217c2ab70f4.PNG)

**Comment by creationix** [comment]
We decided to go with plain spawn on the backend and write a semi-intelligent console client.

<img width="839" alt="screen shot 2016-04-25 at 3 16 09 pm" src="https://cloud.githubusercontent.com/assets/89353/14797385/30063f9a-0af8-11e6-8f98-0f56e296733e.png">

**Comment by harageth** [comment]
Issue didn't properly link to PR #43 so manually closing it.
