### ISSUE TITLE
Design Entity Relations (database tables)

### ISSUE THREAD

**Issue by creationix** [virgo-agent-toolkit/super-agent#4]

**Comment by creationix** [comment]
## Account

This represents customer accounts.
- id
- ...

## Token

Authentication tokens used for agents
- id / token
- account_id

## Agent

Each agent needs a unique id so we can track them
- id
- account_id
- description

## AEP
- id
- public URL

## Agent Connection
- agent_id
- aep_id
- connected_timestamp
- disconnected_timestamp (will be empty while agent is still connected)
- disconnect reason

---

# Common Queries
- authenticate agent - Given agent id and token id, ensure both exist and have same owner, return owner.
- log connection - create agent connection entry
- log disconnect - update agent connection entry
- find agent by id - Query for agent connection with matching id and no disconnect
- get status of all agents for account

---

How can we make the queries about agent connection status fast?

**Comment by harageth** [comment]
Most of these are going to be simple lookups. We just have to make sure that we have indexed across the values we are looking up.

Agent id/token id will need to make sure that in the schema that they are in the same table and have a multi-column key that covers them (I believe that order matters, so we will want to look at which one will be more unique as the first indexed value which assuming that order matters should make the query faster).

**Comment by creationix** [comment]
Ok, I mocked up some sample data in a real postgres.  Looking up the connection status of an agent is simply:

``` sql
SELECT address, connect, disconnect 
  FROM aep, agent_connections 
  WHERE aep.id = agent_connections.aep_id 
    AND agent_connections.agent_id = '00c9a444-b167-41aa-a2df-df95227062dd' 
  ORDER BY connect LIMIT 1;
```

With my tiny data set of just one of everything the explain is pretty boring.  We'll need more sample data to get an idea of how this will scale and what indexes are needed.

<img width="586" alt="screen shot 2016-01-22 at 4 53 06 pm" src="https://cloud.githubusercontent.com/assets/89353/12525247/9ec4df32-c128-11e5-881d-ea7813ff0fec.png">

**Comment by creationix** [comment]
I cleaned up the schema in my sample.  Storing here for reference.

``` sql
CREATE TABLE aep (
    id uuid PRIMARY KEY,
    address text NOT NULL
);
CREATE TABLE account (
    id uuid PRIMARY KEY,
    name text NOT NULL
);
CREATE TABLE token (
    id uuid PRIMARY KEY,
    account_id uuid REFERENCES account(id) ON DELETE CASCADE NOT NULL,
    description text NOT NULL
);
CREATE TABLE agent (
    id uuid PRIMARY KEY,
    account_id uuid REFERENCES account(id) ON DELETE CASCADE NOT NULL,
    description text NOT NULL
);
CREATE TABLE connection (
    aep_id uuid REFERENCES aep(id) ON DELETE CASCADE NOT NULL,
    agent_id uuid REFERENCES agent(id) ON DELETE CASCADE NOT NULL,
    connect timestamp without time zone DEFAULT now() NOT NULL,
    disconnect timestamp without time zone
);
CREATE INDEX agent_connection_idx ON connection (agent_id, connect DESC);
```

**Comment by creationix** [comment]
TODO: add tables for recording audit trail of CRUD actions to  `aep`, `account`, `token` and `agent` tables.

Though we'll also need a place to store the actions the agent performs. Also we'll eventually need a way to stream monitoring events and other data the agents generate.  Perhaps tables in this database isn't the best place for all that information.

**Comment by creationix** [comment]
I now having it using my index for looking up connection status.

``` sql
SELECT address, connect, disconnect 
  FROM aep, connection
  WHERE id = aep_id 
    AND agent_id = '00c9a444-b167-41aa-a2df-df95227062dd' 
  ORDER BY connect DESC LIMIT 1;
```

<img width="426" alt="screen shot 2016-01-22 at 5 45 22 pm" src="https://cloud.githubusercontent.com/assets/89353/12526141/ebdb6b54-c12f-11e5-9c40-cfe829a1e37d.png">

**Comment by creationix** [comment]
I created some bulk mock data and doing a query with 2.5 million connections across 500 accounts with 2500 agents.  The query is still pretty fast.

I added a dynamic lookup for the first agent query (since the generated data is random), but it doesn't affect overall speed since it's so fast in comparison.

``` sql
SELECT address, connect, disconnect 
  FROM aep, connection
  WHERE id = aep_id 
    AND agent_id = (SELECT id FROM agent LIMIT 1)
  ORDER BY connect DESC LIMIT 1;
```

<img width="463" alt="screen shot 2016-01-25 at 3 45 33 pm" src="https://cloud.githubusercontent.com/assets/89353/12565594/be0d90ce-c37a-11e5-89e3-4aa4220f722d.png">

This query runs consistently in 33ms on my laptop.

**Comment by creationix** [comment]
Re-ran the test with 10x the data (2.2Gb of dummy data total with 25 million connections).  It's still consistently between 15 and 34ms for the query, even while the db is under load.

**Comment by creationix** [comment]
Authenticating an agent with token and agent id pair is a very fast query.

``` sql
SELECT token.account_id FROM token, agent 
WHERE token.id = '1f7047c4-cbb5-4200-9346-da5d49c11d90'
AND agent.id = '6f95b4d8-5012-40a6-b8ec-cfc2190fcc7b'
AND agent.account_id = token.account_id;
```

<img width="278" alt="screen shot 2016-01-26 at 10 27 25 am" src="https://cloud.githubusercontent.com/assets/89353/12586814/5f03edd8-c417-11e5-8cd0-e7d5b99a1374.png">

**Comment by creationix** [comment]
Even complex queries like getting the current connection status of all agents for a particular account complete with the connection, and aep location is super fast.

``` sql
SELECT agent.id, agent.description, connect, disconnect, aep_id, address FROM agent, connection, aep
WHERE account_id = 'a21e88c0-5aab-4241-beb1-45cb4b013271'
AND connection.connect = (
  SELECT connect FROM connection
  WHERE agent_id = agent.id 
  ORDER BY connect DESC LIMIT 1)
AND connection.agent_id = agent.id
AND aep.id = connection.aep_id;
```

<img width="765" alt="screen shot 2016-01-26 at 10 47 46 am" src="https://cloud.githubusercontent.com/assets/89353/12587485/37797a28-c41a-11e5-808b-1c1e15c4f859.png">

This query also runs around 33ms (which seems to be the lower limit for any query on my machine).

**Comment by creationix** [comment]
Getting token information for an account is simple now since we don't store much.

``` sql
SELECT id, description FROM token
WHERE account_id = 'a21e88c0-5aab-4241-beb1-45cb4b013271';
```

<img width="281" alt="screen shot 2016-01-26 at 11 03 12 am" src="https://cloud.githubusercontent.com/assets/89353/12588014/5dd00b4a-c41c-11e5-973b-89e308f140a2.png">

But an interesting feature would be to record what token an agent uses to authenticate.  This could go in the already huge connection table and would probably require a new index to add it to this query (last time token was used, how many agents currently use it, etc..)

**Comment by harageth** [comment]
Admittedly I am not sure how postgres handles COPY. Do we know how much of the data is locked while the copy is running?

**Comment by creationix** [comment]
The entire copy is a single transaction.  Nothing is available till it's done.  That's why it's used to insert bulk data.

**Comment by harageth** [comment]
That's what I thought. So these timings are only based on what data was already there but still with a pretty big write load.

**Comment by creationix** [comment]
The times were the same while loading data and after all data was loaded.  All the queries with proper indexes run at a flat 33ms every time.

**Comment by creationix** [comment]
Also the `connection` table was imported in 2,500 different COPY commands to keep memory overhead low.

**Comment by harageth** [comment]
ahhhhh ok. 

Still it seems rather weird that it always runs at a flat 33 ms. It's not something that I am particularly worried about, it just seems weird. And it doesn't change after having run the same query so it isn't a cache/on disk issue. Although it could be because the COPY's would put something in the cache and depending on how much memory you have allowed postgres to start with it probably just kept it in the cache based on the query's that ran.

**Comment by creationix** [comment]
I don't think it's cache related.  I rebooted the laptop, dropped and re-created the indexes, etc.  Nothing really changes the times as long as I have proper indexes.  Now if I don't have proper indexes, it takes forever.

I am a little concerned that the IDs I'm selecting for testing are too near the front.  I'm working on trying to grab indexes known to require more scanning through indexes.
